#!/bin/bash
# One-time setup for VenusFactory2 online mode (per-session kimi sandbox).
#
# Run once on the host as root:
#
#   sudo bash scripts/install/setup-online-mode.sh
#
# Idempotent — re-running just refreshes state. What it does:
#
#   1. Creates the `venus` group (if missing) and adds the project owner
#      (tanyang) so fastapi can rwx session_dirs that DynamicUser writes.
#   2. Installs venus-spawn-kimi to /usr/local/libexec/.
#   3. Installs a sudoers fragment letting tanyang run *only* the spawn
#      helper and stop venus-kimi-*.scope units without password.
#   4. Creates the project-local session root with the right group + perms.
#   5. (Optional) installs the venusfactory.service systemd unit so the
#      fastapi process autostarts on boot.
#
# Designed for the single-machine deployment where fastapi runs as the
# `tanyang` user and frp tunnels port 7861 to the internet.

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
  echo "This script must be run as root: sudo bash $0" >&2
  exit 1
fi

PROJECT_OWNER="${PROJECT_OWNER:-tanyang}"
PROJECT_ROOT="${PROJECT_ROOT:-/home/${PROJECT_OWNER}/workspace/VenusFactory2}"
SESSIONS_DIR="${PROJECT_ROOT}/temp_outputs/web_v2/sessions"
HELPER_SRC="${PROJECT_ROOT}/scripts/install/venus-spawn-kimi"
HELPER_DEST="/usr/local/libexec/venus-spawn-kimi"
SUDOERS_FILE="/etc/sudoers.d/venusfactory"
SYSTEMD_UNIT_DEST="/etc/systemd/system/venusfactory.service"
SYSTEMD_UNIT_SRC="${PROJECT_ROOT}/scripts/install/venusfactory.service"

echo "[1/5] Ensuring 'venus' group exists and includes ${PROJECT_OWNER}..."
if ! getent group venus >/dev/null; then
  groupadd --system venus
  echo "  - created system group 'venus'"
fi
if id -nG "${PROJECT_OWNER}" | tr ' ' '\n' | grep -qx venus; then
  echo "  - ${PROJECT_OWNER} already in venus group"
else
  usermod -aG venus "${PROJECT_OWNER}"
  echo "  - added ${PROJECT_OWNER} to venus group"
  echo "  NOTE: ${PROJECT_OWNER} must log out + back in (or run 'newgrp venus') for new group to take effect."
fi

echo "[2/5] Installing venus-spawn-kimi helper..."
if [[ ! -x "$HELPER_SRC" ]]; then
  echo "  ERROR: helper not found or not executable at $HELPER_SRC" >&2
  exit 2
fi
# /usr/local/libexec/ isn't created by default on Debian/Ubuntu.
mkdir -p "$(dirname "$HELPER_DEST")"
install -m 0755 -o root -g root "$HELPER_SRC" "$HELPER_DEST"
echo "  - installed at $HELPER_DEST"

echo "[3/5] Installing sudoers fragment..."
cat > "${SUDOERS_FILE}.tmp" <<EOF
# VenusFactory2 online-mode helper — auto-generated by setup-online-mode.sh
# Allows fastapi (running as ${PROJECT_OWNER}) to spawn isolated kimi-code
# sessions and stop them without an interactive sudo prompt. Arguments to
# the helper are strictly validated inside the helper itself.
${PROJECT_OWNER} ALL=(root) NOPASSWD: ${HELPER_DEST}
${PROJECT_OWNER} ALL=(root) NOPASSWD: /bin/systemctl stop venus-kimi-*.scope
${PROJECT_OWNER} ALL=(root) NOPASSWD: /bin/systemctl is-active venus-kimi-*.scope
EOF
# visudo -cf validates before installing — corrupt sudoers locks you out.
if visudo -cf "${SUDOERS_FILE}.tmp" >/dev/null; then
  install -m 0440 -o root -g root "${SUDOERS_FILE}.tmp" "${SUDOERS_FILE}"
  rm -f "${SUDOERS_FILE}.tmp"
  echo "  - installed $SUDOERS_FILE"
else
  echo "  ERROR: generated sudoers fragment failed visudo check" >&2
  exit 3
fi

echo "[4/5] Preparing session root at ${SESSIONS_DIR}..."
mkdir -p "$SESSIONS_DIR"
chgrp venus "$SESSIONS_DIR"
chmod 2770 "$SESSIONS_DIR"
# Default ACL is the nicest-to-have but POSIX ACLs aren't supported on
# many shared filesystems (NFS without acl mount option, some bind mounts).
# The setgid bit on a 2770 dir already makes new SUBDIRS inherit the group,
# and files inherit the group too (regardless of ACL). The ACL would only
# add g+rwx on plain files; without it group gets default umask perms
# which on a 0022 umask is g+r — enough for fastapi to LIST and READ files,
# which is what /api/files/inline needs. Write happens via DynamicUser only.
if command -v setfacl >/dev/null; then
  if setfacl -d -m g:venus:rwx "$SESSIONS_DIR" 2>/dev/null; then
    echo "  - set default venus ACL on $SESSIONS_DIR"
  else
    echo "  - setfacl unsupported on this filesystem (likely NFS) — relying on setgid bit"
  fi
else
  echo "  - setfacl not found; relying on setgid bit (install acl pkg if you want default ACLs)"
fi
# Also make sure parent dirs are traversable
chain="${SESSIONS_DIR}"
while [[ "$chain" != "/" ]]; do
  parent="$(dirname "$chain")"
  current_mode=$(stat -c '%a' "$parent" 2>/dev/null || echo "")
  if [[ -n "$current_mode" && ! "$current_mode" =~ [157] ]]; then
    echo "  WARN: $parent mode $current_mode may not allow venus group traversal"
  fi
  chain="$parent"
done
echo "  - $SESSIONS_DIR ready (2770 venus)"

echo "[5/5] systemd unit (optional)..."
if [[ -f "$SYSTEMD_UNIT_SRC" ]]; then
  install -m 0644 -o root -g root "$SYSTEMD_UNIT_SRC" "$SYSTEMD_UNIT_DEST"
  systemctl daemon-reload
  echo "  - installed $SYSTEMD_UNIT_DEST"
  echo "  - enable + start with:  sudo systemctl enable --now venusfactory"
else
  echo "  - skipped (template not present at $SYSTEMD_UNIT_SRC)"
fi

echo
echo "Setup complete. Sanity check:"
echo "  - venus group:   $(getent group venus)"
echo "  - helper:        $(ls -l $HELPER_DEST)"
echo "  - sudoers:       $(ls -l $SUDOERS_FILE)"
echo "  - sessions dir:  $(ls -ld $SESSIONS_DIR)"
echo
echo "Next steps:"
echo "  1. ${PROJECT_OWNER} runs 'newgrp venus' (or re-logs) to pick up new group."
echo "  2. Start fastapi in online mode:"
echo "     WEBUI_V2_MODE=online MCP_HTTP_PORT=8088 python src/webui_v2.py --online --host 0.0.0.0 --port 7861"
echo "  3. Or: sudo systemctl enable --now venusfactory (if you installed the unit)"
